In [1]:
# Codeblock 1
! pip install numpy

In [2]:
# Codeblock 2
import numpy as np
np.__version__

'1.25.0'

In [3]:
# Codeblock 3
np.array([7,6,5,4,3,2])

### Alternative
# np.asarray([7,6,5,4,3,2])

array([7, 6, 5, 4, 3, 2])

In [4]:
# Codeblock 4
print(np.asarray([7,6,5,4,3,2]))

[7 6 5 4 3 2]


In [5]:
# Codeblock 5
[7,6,5,4,3,2]

### Alternative
# print([7,6,5,4,3,2])

[7, 6, 5, 4, 3, 2]

In [6]:
# Codeblock 6
print(np.asarray([[7,6,5,4,3,2], 
                  [9,8,7,6,5,4]]), end='\n\n')

print([[7,6,5,4,3,2], 
       [9,8,7,6,5,4]])

[[7 6 5 4 3 2]
 [9 8 7 6 5 4]]

[[7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4]]


In [7]:
# Codeblock 7
A = [2,4,6,8]
B = np.array(A)   # Convert to Numpy array.
C = B.tolist()    # Convert to Python list.

print(B)
print(C)

[2 4 6 8]
[2, 4, 6, 8]


In [8]:
# Codeblock 8
print('type(A):', type(A))
print('type(B):', type(B))
print('type(C):', type(C))

type(A): <class 'list'>
type(B): <class 'numpy.ndarray'>
type(C): <class 'list'>


In [9]:
# Codeblock 9
np.genfromtxt('data.txt', delimiter=',')

array([[99., 88., 77., 66.],
       [11., 22., 33., 44.]])

In [10]:
# Codeblock 10
D = [2, 'Hello', True, 9.886]
D

[2, 'Hello', True, 9.886]

In [11]:
# Codeblock 11
print(np.array(D))
print(np.array(D).tolist())

['2' 'Hello' 'True' '9.886']
['2', 'Hello', 'True', '9.886']


In [12]:
# Codeblock 12
import time

E = [123] * 9999999
F = np.array(E, dtype='int8')

In [13]:
# Codeblock 13
def summation_python_sum(arr):
    start_time = time.time()
    sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time
    
def summation_numpy_sum(arr):
    start_time = time.time()
    np.sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time

In [14]:
# Codeblock 14
print('Python list with sum()\t\t: ', summation_python_sum(E), 'sec')
print('Python list with np.sum()\t: ', summation_numpy_sum(E), 'sec')
print('Numpy array with sum()\t\t: ', summation_python_sum(F), 'sec')
print('Numpy array with np.sum()\t: ', summation_numpy_sum(F), 'sec')

Python list with sum()		:  0.06290745735168457 sec
Python list with np.sum()	:  0.7632937431335449 sec
Numpy array with sum()		:  1.9828064441680908 sec
Numpy array with np.sum()	:  0.021625757217407227 sec


In [15]:
# Codeblock 15
import sys

print('E (Python list):', sys.getsizeof(E), 'bytes')
print('F (Numpy array):', sys.getsizeof(F), 'bytes')

E (Python list): 80000048 bytes
F (Numpy array): 10000111 bytes


In [16]:
# Codeblock 16
print(B.dtype)
print(F.dtype)

int32
int8


In [17]:
# Codeblock 17
print(np.array([5, 5, 5, 5.3, 5]).dtype)
print(np.array([True, True, False]).dtype)

float64
bool


In [18]:
# Codeblock 18
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [19]:
# Codeblock 19
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

In [20]:
# Codeblock 20
G = np.array([9, 7, 5, 6, 4, 8, 2, 6, 9, 5, 2, 4, 1, 4])

In [21]:
# Codeblock 21
print('G[7]\t\t:', G[7])        #(1)
print('G[-2]\t\t:', G[-2])      #(2)
print('G[:3]\t\t:', G[:3])      #(3)
print('G[3:]\t\t:', G[3:])      #(4)
print('G[2:6]\t\t:', G[2:6])    #(5)
print('G[1:7:2]\t:', G[1:7:2])  #(6)
print('G[::3]\t\t:', G[::3])    #(7)

G[7]		: 6
G[-2]		: 1
G[:3]		: [9 7 5]
G[3:]		: [6 4 8 2 6 9 5 2 4 1 4]
G[2:6]		: [5 6 4 8]
G[1:7:2]	: [7 6 8]
G[::3]		: [9 6 2 5 1]


In [22]:
# Codeblock 22
H = np.array([6,4,5,7,4,3])
print('G[H]\t:', G[H])

G[H]	: [2 4 8 6 4 6]


In [23]:
# Codeblock 23
I = np.array([[3, 1, 5, 7], 
              [2, 5, 3, 2], 
              [3, 8, 5, 9],
              [4, 8, 2, 6]])

In [24]:
# Codeblock 24
I[0,2]

5

In [25]:
# Codeblock 25
I[:2,:3]

array([[3, 1, 5],
       [2, 5, 3]])

In [26]:
# Codeblock 26
I[:,1:3]

array([[1, 5],
       [5, 3],
       [8, 5],
       [8, 2]])

In [27]:
# Codeblock 27
I[:-1,1:3]

array([[1, 5],
       [5, 3],
       [8, 5]])

In [28]:
# Codeblock 28
I[[0,2], :3]

array([[3, 1, 5],
       [3, 8, 5]])

In [29]:
# Codeblock 29
I[[0,1,2], [0,1,2]]

array([3, 5, 5])

In [30]:
# Codeblock 30
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
# Codeblock 31
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# Codeblock 32
np.zeros((4,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [33]:
# Codeblock 33
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
# Codeblock 34
np.eye(N=6, M=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# Codeblock 35
np.diag([1,4,3,4,4])

array([[1, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

In [36]:
# Codeblock 36
np.empty((3,3))

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 9.03e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [37]:
# Codeblock 37
J = np.full(shape=(3,5), fill_value=999)
J

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In [38]:
# Codeblock 38
np.full_like(J, fill_value=111)

array([[111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111]])

In [39]:
# Codeblock 39
print(np.empty_like(J), end='\n\n')
print(np.ones_like(J), end='\n\n')
print(np.zeros_like(J))

[[   0    0    0    0    0]
 [   0    0    0    0    0]
 [1860    0    0    0    0]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [40]:
# Codeblock 40
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
# Codeblock 41
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [42]:
# Codeblock 42
print(np.arange(3, 20, 2), end='\n\n')
print(np.arange(100, 0, -3), end='\n\n')
print(np.arange(20, 30, 0.5))

[ 3  5  7  9 11 13 15 17 19]

[100  97  94  91  88  85  82  79  76  73  70  67  64  61  58  55  52  49
  46  43  40  37  34  31  28  25  22  19  16  13  10   7   4   1]

[20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5
 27.  27.5 28.  28.5 29.  29.5]


In [43]:
# Codeblock 43
np.linspace(1, 15, 50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [44]:
# Codeblock 44
np.geomspace(1, 15, 50)

array([ 1.        ,  1.05682204,  1.11687283,  1.18033582,  1.24740491,
        1.318285  ,  1.39319265,  1.4723567 ,  1.55601901,  1.64443519,
        1.73787535,  1.83662498,  1.94098576,  2.05127653,  2.16783425,
        2.29101502,  2.42119517,  2.55877242,  2.70416709,  2.85782339,
        3.02021075,  3.19182529,  3.37319131,  3.56486293,  3.76742572,
        3.98149854,  4.20773541,  4.44682753,  4.69950535,  4.96654083,
        5.24874982,  5.5469945 ,  5.86218605,  6.19528743,  6.54731631,
        6.91934818,  7.31251967,  7.72803197,  8.16715452,  8.63122891,
        9.12167296,  9.63998503, 10.18774866, 10.76663734, 11.37841965,
       12.02496468, 12.70824772, 13.43035629, 14.19349655, 15.        ])