In [1]:
import numpy as np

In [2]:
# Codeblock 1
np.random.rand(10,3)

### Alternative
# np.random.random((10,3))

array([[0.87795948, 0.71834295, 0.11476649],
       [0.71235696, 0.96316946, 0.63879289],
       [0.95263623, 0.4285279 , 0.7984052 ],
       [0.84241418, 0.34051888, 0.69600689],
       [0.18284161, 0.55107725, 0.09951073],
       [0.37052771, 0.69301478, 0.97324294],
       [0.72414599, 0.53061932, 0.64080504],
       [0.11112488, 0.19274796, 0.80369146],
       [0.20736015, 0.84645646, 0.78715247],
       [0.41865752, 0.5720698 , 0.56006548]])

In [3]:
# Codeblock 2
np.random.uniform(low=90, high=100, size=(5,5))

array([[98.99591296, 98.85724034, 90.60998422, 99.30668703, 94.11285037],
       [98.26738835, 91.42659443, 94.58743394, 91.13097083, 94.77356274],
       [99.89104943, 92.08434003, 94.07307819, 96.75311764, 92.15474227],
       [93.21266059, 95.66651359, 92.39234969, 92.19379027, 99.97853143],
       [97.35547444, 90.74519659, 97.5502148 , 90.61883099, 93.46254612]])

In [4]:
# Codeblock 3
np.histogram(np.random.uniform(size=(50000)))

### Yields similar results
# np.histogram(np.random.rand(50000))
# np.histogram(np.random.random(50000))

(array([5015, 4983, 4971, 4987, 4974, 4987, 5039, 5020, 5061, 4963],
       dtype=int64),
 array([2.94376781e-06, 1.00002428e-01, 2.00001913e-01, 3.00001397e-01,
        4.00000881e-01, 5.00000366e-01, 5.99999850e-01, 6.99999335e-01,
        7.99998819e-01, 8.99998304e-01, 9.99997788e-01]))

In [5]:
# Codeblock 4
np.random.randn(6,4)

array([[-0.22917913, -0.26946   , -0.38110263, -0.90163866],
       [ 0.2246656 ,  0.69667895,  0.23477174, -0.84008622],
       [ 1.24863766, -0.62991932,  0.39750703, -0.11642637],
       [ 0.60148971, -0.62418361,  1.38058558,  1.50621984],
       [ 1.04694514, -0.18265206,  0.26660451, -0.09637222],
       [-1.31459935, -1.03740177,  0.99494312, -0.01113753]])

In [6]:
# Codeblock 5
np.random.normal(loc=8, scale=3, size=(5,5))

array([[ 6.10397213, 14.19336082,  4.18568954,  3.26823528,  5.29720425],
       [ 6.05101422,  8.33009316, 13.59967775, 12.51753238,  8.48451606],
       [ 6.03688367,  8.19199979, 13.26925765,  8.91263266,  9.42173102],
       [11.0179358 , 11.24698877, 10.3014964 ,  5.08338416,  9.4522892 ],
       [ 8.02396515,  8.7748047 , 10.93189712,  5.46683858, 13.66262551]])

In [7]:
# Codeblock 6
np.histogram(np.random.normal(loc=0, scale=1, size=50000))

### Yields similar result
# np.histogram(np.random.randn(50000))

(array([   10,   155,  1375,  6141, 14106, 16203,  9066,  2558,   357,
           29], dtype=int64),
 array([-4.44446431, -3.5871535 , -2.72984269, -1.87253187, -1.01522106,
        -0.15791024,  0.69940057,  1.55671138,  2.4140222 ,  3.27133301,
         4.12864382]))

In [8]:
# Codeblock 7
np.random.randint(low=5, high=10, size=(20,3))

array([[9, 5, 7],
       [6, 6, 5],
       [8, 7, 5],
       [7, 9, 5],
       [8, 7, 8],
       [9, 5, 7],
       [5, 8, 6],
       [9, 5, 7],
       [9, 7, 6],
       [5, 9, 5],
       [8, 6, 5],
       [7, 7, 6],
       [9, 7, 8],
       [8, 8, 5],
       [5, 7, 7],
       [7, 7, 7],
       [8, 8, 7],
       [9, 6, 9],
       [7, 9, 9],
       [5, 8, 5]])

In [9]:
# Codeblock 8
K = np.random.randint(1, 30, size=10)
K

array([22,  4,  3,  9, 28, 13,  9, 24, 13, 21])

In [10]:
# Codeblock 9
print('K before shuffle\t: ', K)
np.random.shuffle(K)
print('K after shuffle\t\t: ', K)

K before shuffle	:  [22  4  3  9 28 13  9 24 13 21]
K after shuffle		:  [ 9  3 28 13 24  9 21  4 13 22]


In [11]:
# Codeblock 10
print(np.random.choice(K), end='\n\n')                #(1)
print(np.random.choice(K, size=(2,3)), end='\n\n')    #(2)
print(np.random.choice(K, size=(2,4), replace=False)) #(3)

24

[[13 21  4]
 [13 24 22]]

[[ 9 24  9 28]
 [13 21  3 13]]


In [12]:
# Codeblock 11
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

array([[1, 3, 9, 8, 9],
       [8, 2, 4, 5, 4]])

In [13]:
# Codeblock 12
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

array([[1, 3, 9, 8, 9],
       [8, 2, 4, 5, 4]])

In [14]:
# Codeblock 13
L = np.array([55, 66, 77, 88, 99])
M = L
print(M)

[55 66 77 88 99]


In [15]:
# Codeblock 14
M[0] = 15
print('L:', L)
print('M:', M)

L: [15 66 77 88 99]
M: [15 66 77 88 99]


In [16]:
# Codeblock 15
L = np.array([55, 66, 77, 88, 99])
M = L.copy()
M[0] = 15

print('L:', L)
print('M:', M)

L: [55 66 77 88 99]
M: [15 66 77 88 99]


In [17]:
# Codeblock 16
N = np.array([1,2,3], dtype='int32')
O = np.array([4,5,6], dtype='int32')

In [18]:
# Codeblock 17
print(N + O)
print(N - O)
print(N * O)
print(N / O)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [19]:
# Codeblock 18
print(np.add(N, O))
print(np.subtract(N, O))
print(np.multiply(N, O))
print(np.divide(N, O))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
# Codeblock 19
print(N + 5)
print(N - 5)
print(N * 5)
print(N / 5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [21]:
# Codeblock 20
O = np.array([[2, 1, 0], 
              [5, 4, 3], 
              [8, 7, 6], 
              [1, 0, 9]])

P = np.array([[4, 3], 
              [6, 5], 
              [8, 7]])

np.matmul(O, P)

array([[ 14,  11],
       [ 68,  56],
       [122, 101],
       [ 76,  66]])

In [22]:
# Codeblock 21
Q = np.array([-56, 92, -24, -66, 72, -75, 90, 0, 32, 51])

print(np.sign(Q))
print(np.negative(Q))
print(np.abs(Q))      # Alternative: np.absolute()

[-1  1 -1 -1  1 -1  1  0  1  1]
[ 56 -92  24  66 -72  75 -90   0 -32 -51]
[56 92 24 66 72 75 90  0 32 51]


In [23]:
# Codeblock 22
print(np.gcd(81, 72))    #(1)
print(np.lcm([3, 6, 9], 24))    #(2)
print(np.lcm([3, 12, 9], [24, 16, 3]))    #(3)

9
[24 24 72]
[24 48  9]


In [24]:
# Codeblock 23
print(np.power(8, 3))
print(np.power([1,2,3,4], 2))
print(np.power(144, 1/2))

512
[ 1  4  9 16]
12.0


In [25]:
# Codeblock 24
print(np.square(6))             # Equivalent with: np.power(6,2)
print(np.sqrt([144,16,9,4]))    # Equivalent with: np.power([144,16,9,4], 1/2)
print(np.cbrt([343,27]))        # Equivalent with: np.power([343,27], 1/3)
print(np.exp([2,3,4]))          # Equivalent with: np.power(np.e, [2,3,4])

36
[12.  4.  3.  2.]
[7. 3.]
[ 7.3890561  20.08553692 54.59815003]


In [26]:
# Codeblock 25
R = np.array([0, 90, 180, 270])    # Angles in degree
S = np.array([0, np.pi/2, np.pi, np.pi*3/2])    # Angles in radian

print(np.deg2rad(R))
print(np.rad2deg(S))

[0.         1.57079633 3.14159265 4.71238898]
[  0.  90. 180. 270.]


In [27]:
# Codeblock 26
T = np.deg2rad([0, 45, 60])

print(np.sin(T))
print(np.cos(T))
print(np.tan(T))

[0.         0.70710678 0.8660254 ]
[1.         0.70710678 0.5       ]
[0.         1.         1.73205081]


In [28]:
# Codeblock 27
U = [1, 2, 10, np.e]

print(np.log(U))
print(np.log2(U))
print(np.log10(U))

[0.         0.69314718 2.30258509 1.        ]
[0.         1.         3.32192809 1.44269504]
[0.         0.30103    1.         0.43429448]


In [29]:
# Codeblock 28
V = np.array([1, 5, 4, 6, 8, 5, 4, 3, 2, 4, 7, 9, 5, 4, 3, 2, 0, 7, 9])

print('sum\t:', np.sum(V))
print('mean\t:', np.mean(V))
print('median\t:', np.median(V))
print('var\t:', np.var(V))
print('stddev\t:', np.std(V))
print('q1\t:', np.quantile(V, 0.25))
print('q2\t:', np.quantile(V, 0.5))
print('q3\t:', np.quantile(V, 0.75))
print('min\t:', np.min(V))
print('max\t:', np.max(V))

sum	: 88
mean	: 4.631578947368421
median	: 4.0
var	: 6.232686980609418
stddev	: 2.4965349948697733
q1	: 3.0
q2	: 4.0
q3	: 6.5
min	: 0
max	: 9


In [30]:
# Codeblock 29
print('argmin\t:', np.argmin(V))
print('argmax\t:', np.argmax(V))

argmin	: 16
argmax	: 11


In [31]:
# Codeblock 30
W = np.array([10, 20, 30, 40])
X = np.array([3, 4, 5, 6])

In [32]:
# Codeblock 31
np.dot(W, X)

500

In [33]:
# Codeblock 32
print(np.inner(W, X))
print(np.outer(W, X))

500
[[ 30  40  50  60]
 [ 60  80 100 120]
 [ 90 120 150 180]
 [120 160 200 240]]


In [34]:
# Codeblock 33
Y = np.array([[2, 1, 0],
              [0, 4, 5],
              [2, 6, 3]])

In [35]:
# Codeblock 34
np.transpose(Y)

### Alternative
# Y.T

array([[2, 0, 2],
       [1, 4, 6],
       [0, 5, 3]])

In [36]:
# Codeblock 35
np.linalg.inv(Y)

array([[ 0.69230769,  0.11538462, -0.19230769],
       [-0.38461538, -0.23076923,  0.38461538],
       [ 0.30769231,  0.38461538, -0.30769231]])

In [37]:
# Codeblock 36
np.linalg.det(Y)

-25.99999999999999

In [38]:
# Codeblock 37
eigenvalues, eigenvectors = np.linalg.eig(Y)

print(eigenvalues, end='\n\n')
print(eigenvectors)

[-1.75212771  1.6260023   9.12612541]

[[-0.17223211 -0.92394503 -0.09751686]
 [ 0.64623686  0.34555331 -0.69491737]
 [-0.74344739 -0.16406855 -0.71244671]]


In [39]:
# Codeblock 38
Z = np.array([True, True, True])
AA = np.array([False, True, True])

In [40]:
# Codeblock 39
print(np.logical_and(Z, AA))
print(np.logical_or(Z, AA))
print(np.logical_xor(Z, AA))

[False  True  True]
[ True  True  True]
[ True False False]


In [41]:
# Codeblock 40
print('np.any(Z): ', np.any(Z))
print('np.all(Z): ', np.all(Z), end='\n\n')
print('np.any(AA):', np.any(AA))
print('np.all(AA):', np.all(AA))

np.any(Z):  True
np.all(Z):  True

np.any(AA): True
np.all(AA): False


In [42]:
# Codeblock 41
AB = np.array([2, 0, 3, -5, 5, -1, 2, -4])

print(np.any(AB > 4))    #(1)
print(np.all(AB > 4))    #(2)

True
False


In [43]:
# Codeblock 42
print(np.bitwise_and(12, 13))
print(np.bitwise_or(12, 13))
print(np.bitwise_xor(12, 13))

12
13
1


In [44]:
# Codeblock 43
print(np.binary_repr(12))
print(np.binary_repr(13))

1100
1101


In [45]:
# Codeblock 44
AC = np.array([9, 4, 5, 3, 2, 6, 8, 6, 5, 4, 5, 5, 3, 2])

mask = AC > 5  #(1)
mask

array([ True, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False])

In [46]:
# Codeblock 45
AC[mask]

array([9, 6, 8, 6])

In [47]:
# Codeblock 46
AC[AC > 5]

array([9, 6, 8, 6])

In [48]:
# Codeblock 47
AC[(AC > 5) & (AC != 9)]

array([6, 8, 6])

In [49]:
# Codeblock 48
AC[np.where((AC > 5) & (AC != 9))]

array([6, 8, 6])

In [50]:
# Codeblock 49
np.where((AC > 5) & (AC != 9))

# Recall the elements of AC: [9, 4, 5, 3, 2, 6, 8, 6, 5, 4, 5, 5, 3, 2].

(array([5, 6, 7], dtype=int64),)

In [51]:
# Codeblock 50
print(AC)
print(np.where(AC > 5, 0, AC+2))

[9 4 5 3 2 6 8 6 5 4 5 5 3 2]
[0 6 7 5 4 0 0 0 7 6 7 7 5 4]


In [52]:
# Codeblock 51
np.unique(AC, return_counts=True)

(array([2, 3, 4, 5, 6, 8, 9]), array([2, 2, 2, 4, 2, 1, 1], dtype=int64))

In [53]:
# Codeblock 52
AD = np.array([77,33,44,99,22,88,55,11,66])
AE = np.array(["Elon Musk", "Bill Gates", "Joe Biden", "Barack Obama"])

print(np.sort(AD))
print(np.sort(AE))

[11 22 33 44 55 66 77 88 99]
['Barack Obama' 'Bill Gates' 'Elon Musk' 'Joe Biden']


In [54]:
# Codeblock 53
print(np.flip(np.sort(AD)))
print(np.flip(np.sort(AE)))

### Alternative
# print(np.sort(AD)[::-1])
# print(np.sort(AE)[::-1])

[99 88 77 66 55 44 33 22 11]
['Joe Biden' 'Elon Musk' 'Bill Gates' 'Barack Obama']


In [55]:
# Codeblock 54
np.argsort(AD)

# Recall the elements of AD: [77, 33, 44, 99, 22, 88, 55, 11, 66].

array([7, 4, 1, 2, 6, 8, 0, 5, 3], dtype=int64)

In [56]:
# Codeblock 55
AD[np.argsort(AD)]

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [57]:
# Codeblock 56
AF = np.array([[3, 1, 5, 7],
               [8, 9, 3, 2], 
               [4, 8, 2, 6]])

In [58]:
# Codeblock 57
print(np.sort(AF, axis=0), end='\n\n')
print(np.sort(AF, axis=1))

[[3 1 2 2]
 [4 8 3 6]
 [8 9 5 7]]

[[1 3 5 7]
 [2 3 8 9]
 [2 4 6 8]]


In [59]:
# Codeblock 58
AG = np.arange(13)
AG

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
# Codeblock 59
print(np.roll(AG, shift=3))     #(1)
print(np.roll(AG, shift=-3))    #(2)

[10 11 12  0  1  2  3  4  5  6  7  8  9]
[ 3  4  5  6  7  8  9 10 11 12  0  1  2]


In [61]:
# Codeblock 60
AH = np.array([[0,   1,  2,  3,  4,  5], 
               [6,   7,  8,  9, 10, 11], 
               [12, 13, 14, 15, 16, 17], 
               [18, 19, 20, 21, 22, 23], 
               [24, 25, 26, 27, 28, 29]])

len(AH)

5

In [62]:
# Codeblock 61
AH.shape

(5, 6)

In [63]:
# Codeblock 62
AH.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
# Codeblock 63
AH.reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [65]:
# Codeblock 64
AH.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
# Codeblock 65
AH.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [67]:
# Codeblock 66
AH.flatten()

### Alternative
# AH.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
# Codeblock 67
AH.flatten()[:, np.newaxis]

### Alternative
# AH.flatten().reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [69]:
# Codeblock 68
AH.flatten()[np.newaxis, :]

### Alternative
# AH.flatten().reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
# Codeblock 69
AI = np.array(np.random.randint(0, 5, (2,4)))
AJ = np.array(np.random.randint(5, 10, (2,4)))

print(AI, end='\n\n')
print(AJ)

[[1 3 1 1]
 [0 3 3 4]]

[[7 5 9 5]
 [5 9 6 8]]


In [71]:
# Codeblock 70
np.vstack((AI,AJ))

array([[1, 3, 1, 1],
       [0, 3, 3, 4],
       [7, 5, 9, 5],
       [5, 9, 6, 8]])

In [72]:
# Codeblock 71
np.hstack((AI,AJ))

array([[1, 3, 1, 1, 7, 5, 9, 5],
       [0, 3, 3, 4, 5, 9, 6, 8]])

In [73]:
# Codeblock 72
print(np.vstack((AI,AJ,AJ,AJ,AI)), end='\n\n')
print(np.hstack((AI,AJ,AJ,AJ,AI)))

[[1 3 1 1]
 [0 3 3 4]
 [7 5 9 5]
 [5 9 6 8]
 [7 5 9 5]
 [5 9 6 8]
 [7 5 9 5]
 [5 9 6 8]
 [1 3 1 1]
 [0 3 3 4]]

[[1 3 1 1 7 5 9 5 7 5 9 5 7 5 9 5 1 3 1 1]
 [0 3 3 4 5 9 6 8 5 9 6 8 5 9 6 8 0 3 3 4]]


In [74]:
# Codeblock 73
print(np.append(AI, AJ), end='\n\n')
print(np.append(AI, AJ, axis=0), end='\n\n')
print(np.append(AI, AJ, axis=1))

[1 3 1 1 0 3 3 4 7 5 9 5 5 9 6 8]

[[1 3 1 1]
 [0 3 3 4]
 [7 5 9 5]
 [5 9 6 8]]

[[1 3 1 1 7 5 9 5]
 [0 3 3 4 5 9 6 8]]


In [75]:
# Codeblock 74
print(np.concatenate([AI, AI, AI], axis=None), end='\n\n')
print(np.concatenate([AI, AI, AI]), end='\n\n')
print(np.concatenate([AI, AI, AI], axis=1))

[1 3 1 1 0 3 3 4 1 3 1 1 0 3 3 4 1 3 1 1 0 3 3 4]

[[1 3 1 1]
 [0 3 3 4]
 [1 3 1 1]
 [0 3 3 4]
 [1 3 1 1]
 [0 3 3 4]]

[[1 3 1 1 1 3 1 1 1 3 1 1]
 [0 3 3 4 0 3 3 4 0 3 3 4]]


In [76]:
# Codeblock 75
AK = np.random.randint(0, 10, (20))
AK

array([7, 5, 4, 9, 1, 9, 0, 5, 9, 3, 3, 6, 2, 5, 0, 5, 1, 2, 1, 9])

In [77]:
# Codeblock 76
np.split(AK, indices_or_sections=[3,5])

[array([7, 5, 4]),
 array([9, 1]),
 array([9, 0, 5, 9, 3, 3, 6, 2, 5, 0, 5, 1, 2, 1, 9])]

In [78]:
# Codeblock 77
AL = np.random.randint(0, 10, (5,6))
AL

array([[1, 3, 8, 8, 9, 2],
       [9, 8, 0, 7, 3, 2],
       [0, 6, 0, 2, 3, 2],
       [8, 3, 5, 5, 9, 4],
       [1, 4, 9, 7, 6, 5]])

In [79]:
# Codeblock 78
np.vsplit(AL, [2,4])

### Alternative
# np.split(AL, [2,4], axis=0)

[array([[1, 3, 8, 8, 9, 2],
        [9, 8, 0, 7, 3, 2]]),
 array([[0, 6, 0, 2, 3, 2],
        [8, 3, 5, 5, 9, 4]]),
 array([[1, 4, 9, 7, 6, 5]])]

In [80]:
# Codeblock 79
np.hsplit(AL, [3,4])

### Alternative
# np.split(AL, [3,4], axis=1) #equivalent

[array([[1, 3, 8],
        [9, 8, 0],
        [0, 6, 0],
        [8, 3, 5],
        [1, 4, 9]]),
 array([[8],
        [7],
        [2],
        [5],
        [7]]),
 array([[9, 2],
        [3, 2],
        [3, 2],
        [9, 4],
        [6, 5]])]